#!/bin/bash
# This script is used to detect changes to the files generated by a make INSTALL
# compared to what are the files included in the Install Shield setup.
# (c) 2013 Messaging Architects
# Author benoitl@netmail.com

if [ "$3"a == a ]
then
	echo "Script to check modification to Netmail Unified UI build"
	echo "(c) 2013 Messaging Architects"
	echo
	echo "Usage $0 <project.ism> <binary_path> <ignored_files.txt>"
	exit 1
fi

PROJECT="$1"
BINPATH="$2"
IGNORED="$3"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TMP="$SCRIPT_DIR/tmp"

# "Step 0) initializing temp dir"
rm -rf "$TMP"
mkdir "$TMP"

# "Step 1) Listing the file included in the install shield project, prefix with 0"
# grep BUILDID_WARP "$PROJECT" | cut -d'<' -f 16 | sed -e 's/td>&lt;BUILDID_WARP&gt;\\binaries/0/' | tr '\\' '/' > "$TMP/is_list.txt"
#grep -i "ARCHI_FI&gt;.Netmail.WebAdmin" "$PROJECT" | cut -d'<' -f 16 | sed -e 's/td>&lt;PATH_TO_MESSAGING ARCHI_FI&gt;\\Netmail WebAdmin/0/I' | tr '\\' '/' > "$TMP/is_list.txt"
grep -i "ARCHI_FI&gt;.Netmail.WebAdmin" "$PROJECT" | sed -r 's/(.*)PATH_TO_MESSAGING/PATH_TO_MESSAGING/g' | sed -r 's/<\/td.*$//g' | sed -e 's/PATH_TO_MESSAGING ARCHI_FI&gt;\\Netmail WebAdmin/0/I' | tr '\\' '/' > "$TMP/is_list.txt"
# "Step 2) Listing the files from the location to be compared, prefix with 1"
DOTS=`echo "$BINPATH" | sed -e 's/././g'`
find "$BINPATH" -type f | sed -e "s/^$DOTS/1/" > "$TMP/build_list.txt"

# "Step 3) List files to be ignored, prefix with 2"
cat "$IGNORED" | tr -d '\r' | while read LINE
do
  if [ -n "$LINE" -a "${LINE:0:1}" != "#" ]
  then
    echo "$BINPATH/$LINE"	
    find "$BINPATH/$LINE" -type f 2>/dev/null
	fi
done | tr '\\' '/' | sed -e "s/^$DOTS/2/" > "$TMP/ignore_list.txt"

# "Step 4) Combine everyting, and find non-duplicate lines, these are files missing from one side or the other"
cat $TMP/*.txt | sort --field-separator=/ --key=2 | uniq --ignore-case --skip-chars=1 -u > "$TMP/combined.txt"

# "Step 5) Lines prefixed with 0 are files that the build no longuer generate"
grep -e '^0/' "$TMP/combined.txt" | sed -e 's/^..//' > "$TMP/missing_build.txt"
if [ -s "$TMP/missing_build.txt" ]
then
	echo
	echo ERROR Found missing files in the build:
	echo
	cat "$TMP/missing_build.txt"
	echo 
	echo "To ignore these files, you can edit <SVN_NETMAIL_PLATFORM>/HudsonBuild/to_ignore_from_install_shield.txt"
	echo
	echo
else
	echo -e "\tNo missing files found in build"
	rm "$TMP/missing_build.txt"
fi

# "Step 6) Lines prefixed with 1 are files that are missing in the install shield"
grep -e '^1/' "$TMP/combined.txt" | sed -e 's/^..//' > "$TMP/missing_install_shield.txt"
if [ -s "$TMP/missing_install_shield.txt" ]
then
	echo
	echo ERROR Found missing files in the install shield: 
	echo
	cat "$TMP/missing_install_shield.txt"
	echo
	echo "To ignore these files, you can edit <SVN_NETMAIL_PLATFORM>/HudsonBuild/to_ignore_from_install_shield.txt"
	echo
	echo
else
	echo -e "\tNo missing files in InstallShield"
	rm "$TMP/missing_install_shield.txt"
fi
